ITERATION_TIMES = 50
ACTIVITY_DEMOMINATOR = 3
INITIAL_LIKELIHOOD = 50
INITIAL_ACTIVITY = 50

CONCETPT_CLD_LIKELIHOOD_UPDATE_TIMES = 3

COOL_DOWN_SWITCH = False
COOL_DOWN_TIMES = 1

# REFERENCE_MODE_PATH = './StockAndFlowInPython/case/linear_decrease.csv'
REFERENCE_MODE_PATH = './StockAndFlowInPython/case/tea_cup_model.csv'
