
# REFERENCE_MODE_PATH = './StockAndFlowInPython/case/linear_decrease.csv'
REFERENCE_MODE_PATH = './StockAndFlowInPython/case/tea_cup_model.csv'
# REFERENCE_MODE_PATH = './StockAndFlowInPython/case/water_sink.csv'

ITERATION_TIMES = 5

ACTIVITY_DEMOMINATOR = 2

INITIAL_LIKELIHOOD = 50
INITIAL_ACTIVITY = 50

CANDIDATE_STRUCTURE_ACTIVITY_UPDATE_TIMES = 3

GENERIC_STRUCTURE_LIKELIHOOD_UPDATE_TIMES = 3

COOL_DOWN_SWITCH = False
COOL_DOWN_TIMES = 1

PURGE_SWITCH = False
PURGE_THRESHOLD = 1
