# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_structure_generator.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_sfd = QtWidgets.QWidget()
        self.tab_sfd.setObjectName("tab_sfd")
        self.layout_sfd = QtWidgets.QVBoxLayout(self.tab_sfd)
        self.layout_sfd.setContentsMargins(0, 0, 0, -1)
        self.layout_sfd.setObjectName("layout_sfd")
        self.tabWidget.addTab(self.tab_sfd, "")
        self.tab_cld = QtWidgets.QWidget()
        self.tab_cld.setObjectName("tab_cld")
        self.layout_cld = QtWidgets.QVBoxLayout(self.tab_cld)
        self.layout_cld.setContentsMargins(0, 0, 0, 0)
        self.layout_cld.setObjectName("layout_cld")
        self.tabWidget.addTab(self.tab_cld, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.widget_simulation_control = QtWidgets.QWidget(self.centralwidget)
        self.widget_simulation_control.setMaximumSize(QtCore.QSize(16777215, 70))
        self.widget_simulation_control.setObjectName("widget_simulation_control")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_simulation_control)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_simulation_buttons = QtWidgets.QWidget(self.widget_simulation_control)
        self.widget_simulation_buttons.setObjectName("widget_simulation_buttons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_simulation_buttons)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_start = QtWidgets.QPushButton(self.widget_simulation_buttons)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_2.addWidget(self.pushButton_start)
        self.pushButton_pause = QtWidgets.QPushButton(self.widget_simulation_buttons)
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.horizontalLayout_2.addWidget(self.pushButton_pause)
        self.pushButton_reset = QtWidgets.QPushButton(self.widget_simulation_buttons)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.horizontalLayout_2.addWidget(self.pushButton_reset)
        self.horizontalLayout.addWidget(self.widget_simulation_buttons)
        self.simulation_slider = QtWidgets.QSlider(self.widget_simulation_control)
        self.simulation_slider.setOrientation(QtCore.Qt.Horizontal)
        self.simulation_slider.setObjectName("simulation_slider")
        self.horizontalLayout.addWidget(self.simulation_slider)
        self.label_time = QtWidgets.QLabel(self.widget_simulation_control)
        self.label_time.setObjectName("label_time")
        self.horizontalLayout.addWidget(self.label_time)
        self.verticalLayout.addWidget(self.widget_simulation_control)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget_browse_time_series = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_browse_time_series.setMinimumSize(QtCore.QSize(215, 274))
        self.dockWidget_browse_time_series.setMaximumSize(QtCore.QSize(300, 524287))
        self.dockWidget_browse_time_series.setObjectName("dockWidget_browse_time_series")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 12, 0, 12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget_2.setMaximumSize(QtCore.QSize(260, 16777215))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_time_series = QtWidgets.QWidget()
        self.tab_time_series.setObjectName("tab_time_series")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_time_series)
        self.verticalLayout_9.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.listWidget_time_series = QtWidgets.QListWidget(self.tab_time_series)
        self.listWidget_time_series.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listWidget_time_series.setObjectName("listWidget_time_series")
        self.verticalLayout_9.addWidget(self.listWidget_time_series, 0, QtCore.Qt.AlignHCenter)
        self.widget_3 = QtWidgets.QWidget(self.tab_time_series)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_ref_type = QtWidgets.QFrame(self.widget_3)
        self.frame_ref_type.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_ref_type.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ref_type.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ref_type.setObjectName("frame_ref_type")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_ref_type)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.radioButton_stock = QtWidgets.QRadioButton(self.frame_ref_type)
        self.radioButton_stock.setMaximumSize(QtCore.QSize(100, 16777215))
        self.radioButton_stock.setObjectName("radioButton_stock")
        self.verticalLayout_11.addWidget(self.radioButton_stock)
        self.radioButton_flow = QtWidgets.QRadioButton(self.frame_ref_type)
        self.radioButton_flow.setMaximumSize(QtCore.QSize(100, 16777215))
        self.radioButton_flow.setObjectName("radioButton_flow")
        self.verticalLayout_11.addWidget(self.radioButton_flow)
        self.radioButton_aux = QtWidgets.QRadioButton(self.frame_ref_type)
        self.radioButton_aux.setMaximumSize(QtCore.QSize(100, 16777215))
        self.radioButton_aux.setObjectName("radioButton_aux")
        self.verticalLayout_11.addWidget(self.radioButton_aux)
        self.horizontalLayout_6.addWidget(self.frame_ref_type)
        self.pushButton_add_ref = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_add_ref.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_add_ref.setObjectName("pushButton_add_ref")
        self.horizontalLayout_6.addWidget(self.pushButton_add_ref)
        self.verticalLayout_9.addWidget(self.widget_3, 0, QtCore.Qt.AlignHCenter)
        self.tabWidget_2.addTab(self.tab_time_series, "")
        self.tab_ref_modes = QtWidgets.QWidget()
        self.tab_ref_modes.setObjectName("tab_ref_modes")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_ref_modes)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.listWidget_reference_modes = QtWidgets.QListWidget(self.tab_ref_modes)
        self.listWidget_reference_modes.setObjectName("listWidget_reference_modes")
        self.verticalLayout_10.addWidget(self.listWidget_reference_modes)
        self.widget_ref_actions = QtWidgets.QWidget(self.tab_ref_modes)
        self.widget_ref_actions.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_ref_actions.setObjectName("widget_ref_actions")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_ref_actions)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_remove_ref = QtWidgets.QPushButton(self.widget_ref_actions)
        self.pushButton_remove_ref.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_remove_ref.setObjectName("pushButton_remove_ref")
        self.horizontalLayout_3.addWidget(self.pushButton_remove_ref)
        self.verticalLayout_10.addWidget(self.widget_ref_actions, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tabWidget_2.addTab(self.tab_ref_modes, "")
        self.verticalLayout_3.addWidget(self.tabWidget_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.dockWidget_browse_time_series.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_browse_time_series)
        self.dockWidget_details = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_details.setMinimumSize(QtCore.QSize(62, 38))
        self.dockWidget_details.setMaximumSize(QtCore.QSize(10000, 10000))
        self.dockWidget_details.setObjectName("dockWidget_details")
        self.dockWidgetContents_details = QtWidgets.QWidget()
        self.dockWidgetContents_details.setObjectName("dockWidgetContents_details")
        self.layout_details = QtWidgets.QVBoxLayout(self.dockWidgetContents_details)
        self.layout_details.setContentsMargins(3, 3, 3, 3)
        self.layout_details.setObjectName("layout_details")
        self.dockWidget_details.setWidget(self.dockWidgetContents_details)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_details)
        self.dockWidget_browse_candidates = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_browse_candidates.setMinimumSize(QtCore.QSize(264, 159))
        self.dockWidget_browse_candidates.setMaximumSize(QtCore.QSize(264, 524287))
        self.dockWidget_browse_candidates.setObjectName("dockWidget_browse_candidates")
        self.dockWidgetContents_candidates = QtWidgets.QWidget()
        self.dockWidgetContents_candidates.setObjectName("dockWidgetContents_candidates")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dockWidgetContents_candidates)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listWidget_candidates = QtWidgets.QListWidget(self.dockWidgetContents_candidates)
        self.listWidget_candidates.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listWidget_candidates.setObjectName("listWidget_candidates")
        self.verticalLayout_4.addWidget(self.listWidget_candidates, 0, QtCore.Qt.AlignHCenter)
        self.widget_candidate_actions = QtWidgets.QWidget(self.dockWidgetContents_candidates)
        self.widget_candidate_actions.setMaximumSize(QtCore.QSize(240, 16777215))
        self.widget_candidate_actions.setObjectName("widget_candidate_actions")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_candidate_actions)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_accept_candidate_structure = QtWidgets.QPushButton(self.widget_candidate_actions)
        self.pushButton_accept_candidate_structure.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_accept_candidate_structure.setObjectName("pushButton_accept_candidate_structure")
        self.horizontalLayout_4.addWidget(self.pushButton_accept_candidate_structure)
        self.pushButton_remove_candidate_structure = QtWidgets.QPushButton(self.widget_candidate_actions)
        self.pushButton_remove_candidate_structure.setObjectName("pushButton_remove_candidate_structure")
        self.horizontalLayout_4.addWidget(self.pushButton_remove_candidate_structure)
        self.pushButton_modify_candidate_structure = QtWidgets.QPushButton(self.widget_candidate_actions)
        self.pushButton_modify_candidate_structure.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_modify_candidate_structure.setObjectName("pushButton_modify_candidate_structure")
        self.horizontalLayout_4.addWidget(self.pushButton_modify_candidate_structure)
        self.verticalLayout_4.addWidget(self.widget_candidate_actions, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.dockWidget_browse_candidates.setWidget(self.dockWidgetContents_candidates)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_browse_candidates)
        self.dockWidget_expansion_tree = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_expansion_tree.setObjectName("dockWidget_expansion_tree")
        self.dockWidgetContents_tree = QtWidgets.QWidget()
        self.dockWidgetContents_tree.setObjectName("dockWidgetContents_tree")
        self.layout_tree = QtWidgets.QVBoxLayout(self.dockWidgetContents_tree)
        self.layout_tree.setContentsMargins(0, 0, 0, 0)
        self.layout_tree.setObjectName("layout_tree")
        self.dockWidget_expansion_tree.setWidget(self.dockWidgetContents_tree)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_expansion_tree)
        self.dockWidget_simulation_result = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_simulation_result.setObjectName("dockWidget_simulation_result")
        self.dockWidgetContents_result = QtWidgets.QWidget()
        self.dockWidgetContents_result.setObjectName("dockWidgetContents_result")
        self.layout_result = QtWidgets.QVBoxLayout(self.dockWidgetContents_result)
        self.layout_result.setContentsMargins(12, 0, 12, 0)
        self.layout_result.setObjectName("layout_result")
        self.widget_select_element = QtWidgets.QWidget(self.dockWidgetContents_result)
        self.widget_select_element.setObjectName("widget_select_element")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_select_element)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_elements = QtWidgets.QLabel(self.widget_select_element)
        self.label_elements.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_elements.setObjectName("label_elements")
        self.horizontalLayout_7.addWidget(self.label_elements)
        self.comboBox_elements = QtWidgets.QComboBox(self.widget_select_element)
        self.comboBox_elements.setObjectName("comboBox_elements")
        self.horizontalLayout_7.addWidget(self.comboBox_elements)
        self.layout_result.addWidget(self.widget_select_element, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.widget_show_behavior = QtWidgets.QWidget(self.dockWidgetContents_result)
        self.widget_show_behavior.setObjectName("widget_show_behavior")
        self.layout_show_behavior = QtWidgets.QVBoxLayout(self.widget_show_behavior)
        self.layout_show_behavior.setContentsMargins(0, 0, 0, 0)
        self.layout_show_behavior.setObjectName("layout_show_behavior")
        self.layout_result.addWidget(self.widget_show_behavior)
        self.dockWidget_simulation_result.setWidget(self.dockWidgetContents_result)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_simulation_result)
        self.dockWidget_bindings = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_bindings.setMinimumSize(QtCore.QSize(173, 159))
        self.dockWidget_bindings.setMaximumSize(QtCore.QSize(260, 524287))
        self.dockWidget_bindings.setObjectName("dockWidget_bindings")
        self.dockWidgetContents_bindings = QtWidgets.QWidget()
        self.dockWidgetContents_bindings.setObjectName("dockWidgetContents_bindings")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dockWidgetContents_bindings)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listWidget_bindings = QtWidgets.QListWidget(self.dockWidgetContents_bindings)
        self.listWidget_bindings.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listWidget_bindings.setObjectName("listWidget_bindings")
        self.verticalLayout_5.addWidget(self.listWidget_bindings, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.widget_binding_actions = QtWidgets.QWidget(self.dockWidgetContents_bindings)
        self.widget_binding_actions.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_binding_actions.setObjectName("widget_binding_actions")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_binding_actions)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_add_binding = QtWidgets.QPushButton(self.widget_binding_actions)
        self.pushButton_add_binding.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_add_binding.setObjectName("pushButton_add_binding")
        self.horizontalLayout_5.addWidget(self.pushButton_add_binding)
        self.pushButton_remove_binding = QtWidgets.QPushButton(self.widget_binding_actions)
        self.pushButton_remove_binding.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_remove_binding.setObjectName("pushButton_remove_binding")
        self.horizontalLayout_5.addWidget(self.pushButton_remove_binding)
        self.verticalLayout_5.addWidget(self.widget_binding_actions, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.dockWidget_bindings.setWidget(self.dockWidgetContents_bindings)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_bindings)
        self.dockWidget_settings = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_settings.setObjectName("dockWidget_settings")
        self.dockWidgetContents_settings = QtWidgets.QWidget()
        self.dockWidgetContents_settings.setObjectName("dockWidgetContents_settings")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents_settings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_settings = QtWidgets.QTabWidget(self.dockWidgetContents_settings)
        self.tabWidget_settings.setObjectName("tabWidget_settings")
        self.tab_iteration = QtWidgets.QWidget()
        self.tab_iteration.setObjectName("tab_iteration")
        self.formLayout = QtWidgets.QFormLayout(self.tab_iteration)
        self.formLayout.setObjectName("formLayout")
        self.label_iteration = QtWidgets.QLabel(self.tab_iteration)
        self.label_iteration.setObjectName("label_iteration")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_iteration)
        self.lineEdit_iteration = QtWidgets.QLineEdit(self.tab_iteration)
        self.lineEdit_iteration.setObjectName("lineEdit_iteration")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_iteration)
        self.tabWidget_settings.addTab(self.tab_iteration, "")
        self.tab_display = QtWidgets.QWidget()
        self.tab_display.setObjectName("tab_display")
        self.tabWidget_settings.addTab(self.tab_display, "")
        self.verticalLayout_2.addWidget(self.tabWidget_settings)
        self.pushButton_apply = QtWidgets.QPushButton(self.dockWidgetContents_settings)
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.verticalLayout_2.addWidget(self.pushButton_apply)
        self.dockWidget_settings.setWidget(self.dockWidgetContents_settings)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_settings)
        self.dockWidget_generic_structures = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_generic_structures.setMinimumSize(QtCore.QSize(150, 117))
        self.dockWidget_generic_structures.setMaximumSize(QtCore.QSize(260, 524287))
        self.dockWidget_generic_structures.setObjectName("dockWidget_generic_structures")
        self.dockWidgetContents_generic_structures = QtWidgets.QWidget()
        self.dockWidgetContents_generic_structures.setObjectName("dockWidgetContents_generic_structures")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dockWidgetContents_generic_structures)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidget_generic_structure = QtWidgets.QTableWidget(self.dockWidgetContents_generic_structures)
        self.tableWidget_generic_structure.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tableWidget_generic_structure.setObjectName("tableWidget_generic_structure")
        self.tableWidget_generic_structure.setColumnCount(0)
        self.tableWidget_generic_structure.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tableWidget_generic_structure, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.dockWidget_generic_structures.setWidget(self.dockWidgetContents_generic_structures)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_generic_structures)
        self.actionStartExpansion = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStartExpansion.setIcon(icon)
        self.actionStartExpansion.setObjectName("actionStartExpansion")
        self.actionStopExpansion = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStopExpansion.setIcon(icon1)
        self.actionStopExpansion.setObjectName("actionStopExpansion")
        self.actionSaveModel = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveModel.setIcon(icon2)
        self.actionSaveModel.setObjectName("actionSaveModel")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon3)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.dockWidget_browse_time_series.raise_()
        self.dockWidget_details.raise_()
        self.dockWidget_browse_candidates.raise_()
        self.dockWidget_simulation_result.raise_()
        self.dockWidget_expansion_tree.raise_()
        self.dockWidget_bindings.raise_()
        self.dockWidget_settings.raise_()
        self.dockWidget_generic_structures.raise_()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionStartExpansion)
        self.toolBar.addAction(self.actionStopExpansion)
        self.toolBar.addAction(self.actionSaveModel)
        self.toolBar.addAction(self.actionExit)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_settings.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Structure Generator"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sfd), _translate("MainWindow", "Stock and Flow Diagram"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cld), _translate("MainWindow", "Causal Loop Diagram"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.pushButton_pause.setText(_translate("MainWindow", "Pause"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset"))
        self.label_time.setText(_translate("MainWindow", "00:00"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dockWidget_browse_time_series.setWindowTitle(_translate("MainWindow", "Time series"))
        self.radioButton_stock.setText(_translate("MainWindow", "Stock"))
        self.radioButton_flow.setText(_translate("MainWindow", "Flow"))
        self.radioButton_aux.setText(_translate("MainWindow", "Auxiliary"))
        self.pushButton_add_ref.setText(_translate("MainWindow", "Add as Ref"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_time_series), _translate("MainWindow", "Time series"))
        self.pushButton_remove_ref.setText(_translate("MainWindow", "Remove"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_ref_modes), _translate("MainWindow", "Reference"))
        self.dockWidget_details.setWindowTitle(_translate("MainWindow", "Details"))
        self.dockWidget_browse_candidates.setWindowTitle(_translate("MainWindow", "Candidate structures"))
        self.pushButton_accept_candidate_structure.setText(_translate("MainWindow", "Accept"))
        self.pushButton_remove_candidate_structure.setText(_translate("MainWindow", "Remove"))
        self.pushButton_modify_candidate_structure.setText(_translate("MainWindow", "Modify"))
        self.dockWidget_expansion_tree.setWindowTitle(_translate("MainWindow", "Expansion tree"))
        self.dockWidget_simulation_result.setWindowTitle(_translate("MainWindow", "Simulation result"))
        self.label_elements.setText(_translate("MainWindow", "Element"))
        self.dockWidget_bindings.setWindowTitle(_translate("MainWindow", "Bindings"))
        self.pushButton_add_binding.setText(_translate("MainWindow", "Add"))
        self.pushButton_remove_binding.setText(_translate("MainWindow", "Remove"))
        self.dockWidget_settings.setWindowTitle(_translate("MainWindow", "Settings"))
        self.label_iteration.setText(_translate("MainWindow", "Iterations:"))
        self.tabWidget_settings.setTabText(self.tabWidget_settings.indexOf(self.tab_iteration), _translate("MainWindow", "Iteration"))
        self.tabWidget_settings.setTabText(self.tabWidget_settings.indexOf(self.tab_display), _translate("MainWindow", "Display"))
        self.pushButton_apply.setText(_translate("MainWindow", "Apply"))
        self.dockWidget_generic_structures.setWindowTitle(_translate("MainWindow", "Generic structures"))
        self.actionStartExpansion.setText(_translate("MainWindow", "Start Expansion"))
        self.actionStopExpansion.setText(_translate("MainWindow", "Stop Expansion"))
        self.actionSaveModel.setText(_translate("MainWindow", "Save Model"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
