# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_structure_generator.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_sfd = QtWidgets.QWidget()
        self.tab_sfd.setObjectName("tab_sfd")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_sfd)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_sfd = QtWidgets.QFrame(self.tab_sfd)
        self.frame_sfd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_sfd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sfd.setObjectName("frame_sfd")
        self.verticalLayout_7.addWidget(self.frame_sfd)
        self.tabWidget.addTab(self.tab_sfd, "")
        self.tab_cld = QtWidgets.QWidget()
        self.tab_cld.setObjectName("tab_cld")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_cld)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_cld = QtWidgets.QFrame(self.tab_cld)
        self.frame_cld.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_cld.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_cld.setObjectName("frame_cld")
        self.verticalLayout_8.addWidget(self.frame_cld)
        self.tabWidget.addTab(self.tab_cld, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.widget_simulation_control = QtWidgets.QWidget(self.centralwidget)
        self.widget_simulation_control.setMaximumSize(QtCore.QSize(16777215, 70))
        self.widget_simulation_control.setObjectName("widget_simulation_control")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_simulation_control)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_simulation_buttons = QtWidgets.QWidget(self.widget_simulation_control)
        self.widget_simulation_buttons.setObjectName("widget_simulation_buttons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_simulation_buttons)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_start = QtWidgets.QPushButton(self.widget_simulation_buttons)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_2.addWidget(self.pushButton_start)
        self.pushButton_pause = QtWidgets.QPushButton(self.widget_simulation_buttons)
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.horizontalLayout_2.addWidget(self.pushButton_pause)
        self.pushButton_reset = QtWidgets.QPushButton(self.widget_simulation_buttons)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.horizontalLayout_2.addWidget(self.pushButton_reset)
        self.horizontalLayout.addWidget(self.widget_simulation_buttons)
        self.simulation_slider = QtWidgets.QSlider(self.widget_simulation_control)
        self.simulation_slider.setOrientation(QtCore.Qt.Horizontal)
        self.simulation_slider.setObjectName("simulation_slider")
        self.horizontalLayout.addWidget(self.simulation_slider)
        self.label_time = QtWidgets.QLabel(self.widget_simulation_control)
        self.label_time.setObjectName("label_time")
        self.horizontalLayout.addWidget(self.label_time)
        self.verticalLayout.addWidget(self.widget_simulation_control)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget_browse_refs = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_browse_refs.setMinimumSize(QtCore.QSize(200, 117))
        self.dockWidget_browse_refs.setObjectName("dockWidget_browse_refs")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget_reference_modes = QtWidgets.QListWidget(self.dockWidgetContents)
        self.listWidget_reference_modes.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listWidget_reference_modes.setObjectName("listWidget_reference_modes")
        self.verticalLayout_3.addWidget(self.listWidget_reference_modes)
        self.dockWidget_browse_refs.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_browse_refs)
        self.dockWidget_details = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_details.setMinimumSize(QtCore.QSize(300, 38))
        self.dockWidget_details.setObjectName("dockWidget_details")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.dockWidget_details.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_details)
        self.dockWidget_browse_candidates = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_browse_candidates.setObjectName("dockWidget_browse_candidates")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget_candidate_structures = QtWidgets.QTableWidget(self.dockWidgetContents_3)
        self.tableWidget_candidate_structures.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tableWidget_candidate_structures.setObjectName("tableWidget_candidate_structures")
        self.tableWidget_candidate_structures.setColumnCount(0)
        self.tableWidget_candidate_structures.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget_candidate_structures)
        self.dockWidget_browse_candidates.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_browse_candidates)
        self.dockWidget_expansion_tree = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_expansion_tree.setObjectName("dockWidget_expansion_tree")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.dockWidget_expansion_tree.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_expansion_tree)
        self.dockWidget_simulation_result = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_simulation_result.setObjectName("dockWidget_simulation_result")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.dockWidget_simulation_result.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_simulation_result)
        self.dockWidget_bindings = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_bindings.setObjectName("dockWidget_bindings")
        self.dockWidgetContents_6 = QtWidgets.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dockWidgetContents_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listWidget_bindings = QtWidgets.QListWidget(self.dockWidgetContents_6)
        self.listWidget_bindings.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listWidget_bindings.setObjectName("listWidget_bindings")
        self.verticalLayout_5.addWidget(self.listWidget_bindings)
        self.dockWidget_bindings.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_bindings)
        self.dockWidget_settings = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_settings.setObjectName("dockWidget_settings")
        self.dockWidgetContents_7 = QtWidgets.QWidget()
        self.dockWidgetContents_7.setObjectName("dockWidgetContents_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents_7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_settings = QtWidgets.QTabWidget(self.dockWidgetContents_7)
        self.tabWidget_settings.setObjectName("tabWidget_settings")
        self.tab_iteration = QtWidgets.QWidget()
        self.tab_iteration.setObjectName("tab_iteration")
        self.formLayout = QtWidgets.QFormLayout(self.tab_iteration)
        self.formLayout.setObjectName("formLayout")
        self.label_iteration = QtWidgets.QLabel(self.tab_iteration)
        self.label_iteration.setObjectName("label_iteration")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_iteration)
        self.lineEdit_iteration = QtWidgets.QLineEdit(self.tab_iteration)
        self.lineEdit_iteration.setObjectName("lineEdit_iteration")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_iteration)
        self.tabWidget_settings.addTab(self.tab_iteration, "")
        self.tab_display = QtWidgets.QWidget()
        self.tab_display.setObjectName("tab_display")
        self.tabWidget_settings.addTab(self.tab_display, "")
        self.verticalLayout_2.addWidget(self.tabWidget_settings)
        self.pushButton_apply = QtWidgets.QPushButton(self.dockWidgetContents_7)
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.verticalLayout_2.addWidget(self.pushButton_apply)
        self.dockWidget_settings.setWidget(self.dockWidgetContents_7)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_settings)
        self.dockWidget_generic_structures = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_generic_structures.setObjectName("dockWidget_generic_structures")
        self.dockWidgetContents_8 = QtWidgets.QWidget()
        self.dockWidgetContents_8.setObjectName("dockWidgetContents_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dockWidgetContents_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidget_generic_structure = QtWidgets.QTableWidget(self.dockWidgetContents_8)
        self.tableWidget_generic_structure.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tableWidget_generic_structure.setObjectName("tableWidget_generic_structure")
        self.tableWidget_generic_structure.setColumnCount(0)
        self.tableWidget_generic_structure.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tableWidget_generic_structure)
        self.dockWidget_generic_structures.setWidget(self.dockWidgetContents_8)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_generic_structures)
        self.actionStartExpansion = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStartExpansion.setIcon(icon)
        self.actionStartExpansion.setObjectName("actionStartExpansion")
        self.actionStopExpansion = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStopExpansion.setIcon(icon1)
        self.actionStopExpansion.setObjectName("actionStopExpansion")
        self.actionSaveModel = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveModel.setIcon(icon2)
        self.actionSaveModel.setObjectName("actionSaveModel")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon3)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.dockWidget_browse_refs.raise_()
        self.dockWidget_details.raise_()
        self.dockWidget_browse_candidates.raise_()
        self.dockWidget_simulation_result.raise_()
        self.dockWidget_expansion_tree.raise_()
        self.dockWidget_bindings.raise_()
        self.dockWidget_settings.raise_()
        self.dockWidget_generic_structures.raise_()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionStartExpansion)
        self.toolBar.addAction(self.actionStopExpansion)
        self.toolBar.addAction(self.actionSaveModel)
        self.toolBar.addAction(self.actionExit)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_settings.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Structure Generator"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sfd), _translate("MainWindow", "Stock and Flow Diagram"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cld), _translate("MainWindow", "Causal Loop Diagram"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.pushButton_pause.setText(_translate("MainWindow", "Pause"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset"))
        self.label_time.setText(_translate("MainWindow", "00:00"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dockWidget_browse_refs.setWindowTitle(_translate("MainWindow", "Reference modes"))
        self.dockWidget_details.setWindowTitle(_translate("MainWindow", "Details"))
        self.dockWidget_browse_candidates.setWindowTitle(_translate("MainWindow", "Candidate structures"))
        self.dockWidget_expansion_tree.setWindowTitle(_translate("MainWindow", "Expansion tree"))
        self.dockWidget_simulation_result.setWindowTitle(_translate("MainWindow", "Simulation result"))
        self.dockWidget_bindings.setWindowTitle(_translate("MainWindow", "Bindings"))
        self.dockWidget_settings.setWindowTitle(_translate("MainWindow", "Settings"))
        self.label_iteration.setText(_translate("MainWindow", "Iterations:"))
        self.tabWidget_settings.setTabText(self.tabWidget_settings.indexOf(self.tab_iteration), _translate("MainWindow", "Iteration"))
        self.tabWidget_settings.setTabText(self.tabWidget_settings.indexOf(self.tab_display), _translate("MainWindow", "Display"))
        self.pushButton_apply.setText(_translate("MainWindow", "Apply"))
        self.dockWidget_generic_structures.setWindowTitle(_translate("MainWindow", "Generic structures"))
        self.actionStartExpansion.setText(_translate("MainWindow", "Start Expansion"))
        self.actionStopExpansion.setText(_translate("MainWindow", "Stop Expansion"))
        self.actionSaveModel.setText(_translate("MainWindow", "Save Model"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
